/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dandeeee_jnidemo_NativeCallsClass */

#ifndef _Included_com_dandeeee_jnidemo_NativeCallsClass
#define _Included_com_dandeeee_jnidemo_NativeCallsClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dandeeee_jnidemo_NativeCallsClass
 * Method:    printOne
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dandeeee_jnidemo_NativeCallsClass_printOne
  (JNIEnv *, jclass);

/*
 * Class:     com_dandeeee_jnidemo_NativeCallsClass
 * Method:    printTwo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dandeeee_jnidemo_NativeCallsClass_printTwo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
